In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

### Concatenating data

In [2]:
DF_obj=DataFrame(np.arange(49).reshape(7,7))
DF_obj

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
5  35  36  37  38  39  40  41
6  42  43  44  45  46  47  48

In [3]:
DF_obj2=DataFrame(np.arange(16).reshape(4,4))
DF_obj2

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [4]:
pd.concat([DF_obj,DF_obj2],axis=1)

    0   1   2   3   4   5   6     0     1     2     3
0   0   1   2   3   4   5   6   0.0   1.0   2.0   3.0
1   7   8   9  10  11  12  13   4.0   5.0   6.0   7.0
2  14  15  16  17  18  19  20   8.0   9.0  10.0  11.0
3  21  22  23  24  25  26  27  12.0  13.0  14.0  15.0
4  28  29  30  31  32  33  34   NaN   NaN   NaN   NaN
5  35  36  37  38  39  40  41   NaN   NaN   NaN   NaN
6  42  43  44  45  46  47  48   NaN   NaN   NaN   NaN

In [5]:
pd.concat([DF_obj,DF_obj2])

    0   1   2   3     4     5     6
0   0   1   2   3   4.0   5.0   6.0
1   7   8   9  10  11.0  12.0  13.0
2  14  15  16  17  18.0  19.0  20.0
3  21  22  23  24  25.0  26.0  27.0
4  28  29  30  31  32.0  33.0  34.0
5  35  36  37  38  39.0  40.0  41.0
6  42  43  44  45  46.0  47.0  48.0
0   0   1   2   3   NaN   NaN   NaN
1   4   5   6   7   NaN   NaN   NaN
2   8   9  10  11   NaN   NaN   NaN
3  12  13  14  15   NaN   NaN   NaN

### Transforming data
#### Dropping data

In [6]:
DF_obj.drop([1,2])

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
5  35  36  37  38  39  40  41
6  42  43  44  45  46  47  48

In [7]:
DF_obj.drop([1,2,3],axis=1)

    0   4   5   6
0   0   4   5   6
1   7  11  12  13
2  14  18  19  20
3  21  25  26  27
4  28  32  33  34
5  35  39  40  41
6  42  46  47  48

#### Adding data

In [8]:
series_obj=Series(np.arange(10))
series_obj.name='my_series'
series_obj

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: my_series, dtype: int64

In [9]:
variable_add = DataFrame.join(DF_obj, series_obj)
variable_add

    0   1   2   3   4   5   6  my_series
0   0   1   2   3   4   5   6          0
1   7   8   9  10  11  12  13          1
2  14  15  16  17  18  19  20          2
3  21  22  23  24  25  26  27          3
4  28  29  30  31  32  33  34          4
5  35  36  37  38  39  40  41          5
6  42  43  44  45  46  47  48          6

In [10]:
added_datatable = pd.concat([variable_add,variable_add], ignore_index=False)
added_datatable

    0   1   2   3   4   5   6  my_series
0   0   1   2   3   4   5   6          0
1   7   8   9  10  11  12  13          1
2  14  15  16  17  18  19  20          2
3  21  22  23  24  25  26  27          3
4  28  29  30  31  32  33  34          4
5  35  36  37  38  39  40  41          5
6  42  43  44  45  46  47  48          6
0   0   1   2   3   4   5   6          0
1   7   8   9  10  11  12  13          1
2  14  15  16  17  18  19  20          2
3  21  22  23  24  25  26  27          3
4  28  29  30  31  32  33  34          4
5  35  36  37  38  39  40  41          5
6  42  43  44  45  46  47  48          6

In [11]:
added_datatable = pd.concat([variable_add,variable_add], ignore_index=True)
added_datatable

     0   1   2   3   4   5   6  my_series
0    0   1   2   3   4   5   6          0
1    7   8   9  10  11  12  13          1
2   14  15  16  17  18  19  20          2
3   21  22  23  24  25  26  27          3
4   28  29  30  31  32  33  34          4
5   35  36  37  38  39  40  41          5
6   42  43  44  45  46  47  48          6
7    0   1   2   3   4   5   6          0
8    7   8   9  10  11  12  13          1
9   14  15  16  17  18  19  20          2
10  21  22  23  24  25  26  27          3
11  28  29  30  31  32  33  34          4
12  35  36  37  38  39  40  41          5
13  42  43  44  45  46  47  48          6

#### Sorting data

In [12]:
DF_sorted = DF_obj.sort_values(by=[5], ascending=False)
DF_sorted

    0   1   2   3   4   5   6
6  42  43  44  45  46  47  48
5  35  36  37  38  39  40  41
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6