## Working with Missing Data in Pandas

In [20]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [21]:
data ={'name':['John', 'Jane', 'Mary', 'Mark', 'Bob', 'Alice', 'Tom'],'age':[23, 25, 22, 24, 27, 21, 26],'gender':['M', 'F', 'F', 'M', 'M', 'F', 'M'],'rank':[1, 2, 3, 4, 5, 6, 7]} 

ranking_df = DataFrame(data)
ranking_df.iloc[2:5, 1]=np.nan
ranking_df.iloc[3:6, 3]=np.nan
ranking_df.iloc[3, :]=np.nan

ranking_df

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary   NaN      F   3.0
3    NaN   NaN    NaN   NaN
4    Bob   NaN      M   NaN
5  Alice  21.0      F   NaN
6    Tom  26.0      M   7.0

In [22]:
ranking_df.isnull()

    name    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [23]:
ranking_df.notnull()

    name    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [24]:
bool_series=pd.isnull(ranking_df['age'])
ranking_df[bool_series]

   name  age gender  rank
2  Mary  NaN      F   3.0
3   NaN  NaN    NaN   NaN
4   Bob  NaN      M   NaN

In [25]:
ranking_df.fillna(0)

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary   0.0      F   3.0
3      0   0.0      0   0.0
4    Bob   0.0      M   0.0
5  Alice  21.0      F   0.0
6    Tom  26.0      M   7.0

In [35]:
ranking_df=ranking_df.ffill()
ranking_df

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0

In [37]:
ranking_df=ranking_df.bfill()
ranking_df

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0

In [43]:
ranking_df.dropna()

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0

In [44]:
ranking_df.dropna(how='all')

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0

In [45]:
ranking_df.dropna(axis=1)

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0

In [46]:
ranking_df.dropna(axis=0)

    name   age gender  rank
0   John  23.0      M   1.0
1   Jane  25.0      F   2.0
2   Mary  25.0      F   3.0
3   Mary  25.0      F   3.0
4    Bob  25.0      M   3.0
5  Alice  21.0      F   3.0
6    Tom  26.0      M   7.0