## Data Filtering and Selection

In [2]:
!pip install --upgrade pip 
!pip install pandas

Requirement already satisfied: pip in /usr/local/python/3.12.1/lib/python3.12/site-packages (26.1.1)
Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [ ]:
numbers_df = DataFrame(np.arange(0,90,3).reshape(10,3), index=['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10'], columns=['col1','col2','col3'])

In [5]:
numbers_df

       col1  col2  col3
row1      0     3     6
row2      9    12    15
row3     18    21    24
row4     27    30    33
row5     36    39    42
row6     45    48    51
row7     54    57    60
row8     63    66    69
row9     72    75    78
row10    81    84    87

In [6]:
numbers_df.iloc[0,1]

np.int64(3)

In [7]:
numbers_df.iloc[0,1]=20

In [8]:
numbers_df

       col1  col2  col3
row1      0    20     6
row2      9    12    15
row3     18    21    24
row4     27    30    33
row5     36    39    42
row6     45    48    51
row7     54    57    60
row8     63    66    69
row9     72    75    78
row10    81    84    87

In [11]:
numbers_df.iloc[[1,2,4,6],[0,1,2]]

      col1  col2  col3
row2     9    12    15
row3    18    21    24
row5    36    39    42
row7    54    57    60

#### Comparison operators (> < = <= => == !=) and Masking.

In [13]:
mask = numbers_df > 40
mask

        col1   col2   col3
row1   False  False  False
row2   False  False  False
row3   False  False  False
row4   False  False  False
row5   False  False   True
row6    True   True   True
row7    True   True   True
row8    True   True   True
row9    True   True   True
row10   True   True   True

In [14]:
numbers_df[mask]

       col1  col2  col3
row1    NaN   NaN   NaN
row2    NaN   NaN   NaN
row3    NaN   NaN   NaN
row4    NaN   NaN   NaN
row5    NaN   NaN  42.0
row6   45.0  48.0  51.0
row7   54.0  57.0  60.0
row8   63.0  66.0  69.0
row9   72.0  75.0  78.0
row10  81.0  84.0  87.0

In [15]:
numbers_df[numbers_df>50]=0
numbers_df

       col1  col2  col3
row1      0    20     6
row2      9    12    15
row3     18    21    24
row4     27    30    33
row5     36    39    42
row6     45    48     0
row7      0     0     0
row8      0     0     0
row9      0     0     0
row10     0     0     0

In [16]:
numbers_df.iloc[2:6, 1:3]

      col2  col3
row3    21    24
row4    30    33
row5    39    42
row6    48     0